# Generated by Django 4.2.7 on 2024-07-09 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0025_user_did_sports_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_score_type', models.PositiveSmallIntegerField(choices=[(1, 'Natural Sciences'), (2, 'Humanitarian Sciences'), (3, 'General Sciences')])),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('rating', models.PositiveSmallIntegerField()),
                ('main_score', models.FloatField()),
                ('ort_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('english_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manas_admissions.department')),
            ],
            options={
                'unique_together': {('number', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('natural_sciences_score', models.FloatField()),
                ('humanitarian_sciences_score', models.FloatField()),
                ('general_sciences_score', models.FloatField()),
                ('ort_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('english_score', models.FloatField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manas_admissions.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('user', 'number')},
            },
        ),
    ]
