# Generated by Django 4.2.7 on 2024-07-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manas_admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
